name: FTSEngine
author: halberfan
main: de.ftscraft.ftsengine.main.Engine
version: '1.22.2'
api-version: 1.20
depend: [Vault, ProtocolLib, LuckPerms]
softdepend: [Shopkeepers, Dynmap]

commands:
    ausweis:
    würfel:
    countdown:
    spielzeit:
    zauber:
    #roleplay:
    reiten:
    taube:
    schlagen:
    buch:
    removearmorstand:
        premission: ftsengine.armorstand
    #pferd:
    reisepunkt:
    brief:
    gehen:
    klopfen:
    winken:
    umarmen:
    ohrfeige:
    kurier:
    fasten:
    item:
    spucken:
    ftsengine:
    küssen:
    ewürfel: