name: FTSEngine
author: halberfan aka. DoubleTropple
main: de.ftscraft.ftsengine.main.Engine
version: 0.6

commands:
    ausweis:
    würfel:
    countdown:
    roleplay:
    reiten:
    taube:
    schlagen:
    removearmorstand:
        premission: ftsengine.armorstand
    pferd:
    reisepunkt:
    brief: