name: FTSEngine
author: halberfan
main: de.ftscraft.ftsengine.main.Engine
version: ${project.version}
api-version: 1.21
depend: [ Vault, FTSUtils ]
softdepend: [ ProtocolLib, Shopkeepers ]

commands:
  ausweis:
  countdown:
  spielzeit:
  reiten:
  taube:
  schlagen:
  buch:
  removearmorstand:
    premission: ftsengine.armorstand
  durchsuchen:
  reisepunkt:
  brief:
  gehen:
  klopfen:
  winken:
  umarmen:
  ohrfeige:
  kurier:
  fasten:
  item:
  spucken:
  ftsengine:
  küssen:
  ewürfel:
  zeit:
  searchreact:
  streicheln:
  lehrtafel:
