name: FTSEngine
author: halberfan
main: de.ftscraft.ftsengine.main.Engine
version: 1.0.3.1
api-version: 1.14
depend: [Vault, ProtocolLib, LuckPerms]

commands:
    ausweis:
    würfel:
    countdown:
    #roleplay:
    reiten:
    taube:
    schlagen:
    removearmorstand:
        premission: ftsengine.armorstand
    #pferd:
    reisepunkt:
    brief:
    gehen:
    klopfen:
    kurier:
    fasten:
    item: