name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Get current version
        id: version
        run: |
          current=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          base=${current%-SNAPSHOT}
          IFS='.' read -r major minor patch <<< "$base"
          patch=$((patch + 1))
          new_version="${major}.${minor}.${patch}-SNAPSHOT"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Update pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ steps.version.outputs.new_version }}
          mvn versions:commit

      - name: Set git remote with token for authenticated push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Create release branch
        run: |
          git checkout -b release/v${{ steps.version.outputs.new_version }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Release v${{ steps.version.outputs.new_version }}"
          git push origin release/v${{ steps.version.outputs.new_version }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          branch: release/v${{ steps.version.outputs.new_version }}
          title: "Release v${{ steps.version.outputs.new_version }}"
          body: "Automated release of version ${{ steps.version.outputs.new_version }}"
          base: master
          draft: false

      - name: Enable auto-merge
        run: |
          pr_number=$(echo "${{ steps.create_pr.outputs.pull-request-url }}" | grep -oE '[0-9]+$')
          gh pr merge $pr_number --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
