name: Publish and Build
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: mvn clean package
    - run: find . -name "FTSEngine*.jar"
    - uses: actions/upload-artifact@v4
      with:
        name: 'FTSEngine (Dev Build)'
        path: ./target/FTSEngine*.jar
