name: Publish and Build

on: 
  push:
    branches:
      - '**'  # Dies sorgt dafür, dass auf jedem Branch gepusht werden kann

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: mvn clean package
    
  archive:
    needs: build
    if: github.ref == 'refs/heads/master'  # Dieser Job wird nur ausgeführt, wenn auf den Master-Branch gepusht wird
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: mvn clean package
    - run: find . -name "FTSEngine*.jar"
    - uses: actions/upload-artifact@v4
      with:
        name: 'FTSEngine (Master Build)'
        path: ./target/FTSEngine*.jar
